### ISSUE TITLE
[feat] 사용자 로그인 유즈케이스 구현 준비

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#1]
## 🛠 Issue
- 사용자 로그인 유즈케이스를 개발할 수 있도록 User, Auth 도메인의 행동을 설정하고, 행동을 점검할 수 있는 테스트를 작성합니다.

## 📝 To-do
- [x] UserService, AuthService 정의 및 테스트 작성
- [x] AuthPlatformService, AuthTokenService 정의 및 테스트 작성
- [x] AuthRepository 정의 및 테스트 작성

<img width="1091" alt="image" src="https://github.com/Team-Recordy/Recordy-Server/assets/137763434/3e8f8c98-594e-4fbb-814d-93108a0b0757">
