### ISSUE TITLE
[refactor] cloudfront 코드 리팩토링

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#106]
## 🛠 Issue

- RecordService 내 cloudfront와 관련한 코드 추출
- FakeContainer를 서비스 테스트가 상속해서 활용할 수 있도록 수정
- NotFoundException을 리포지토리 단에서 처리할 수 있도록 수정

## 📝 To-do

- [x] RecordService 내 cloudfront와 관련한 코드를 S3Service로 이전
- [x] FakeContainer를 서비스 테스트가 상속해서 활용할 수 있도록 수정
- [ ] NotFoundException을 리포지토리 단에서 처리할 수 있도록 수정
