### ISSUE TITLE
[fix] 배포 서버 Redis 문제 해결 및 블루-그린 배포 적용

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#11]
## 🛠 Issue
- 현재 클라우드 서버에 Redis가 없는 것을 고려하여, 도커 컴포즈를 적용하여 Redis 이미지를 풀하도록 합니다.
- 블루-그린 배포 적용하도록 배포 셸 파일 작성하여 깃헙 액션 통해서 클라우드 서버에 적용합니다.

## 📝 To-do
- [ ] 도커 컴포즈 파일 작성
- [ ] 배포 셸 파일 작성
- [ ] 깃헙 액션 통해 클라우드 서버에 적용
