### ISSUE TITLE
불필요한 API 제거, 서비스 계층 올리기

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#111]
## 🛠 Issue

- 이전 인기순과 같은 불필요한 API를 컨트롤러 ~ 리포지토리까지 모두 제거합니다.
- 프로필 수정 API를 추가합니다.
- 서비스 계층까지 올립니다.

## 📝 To-do

- [x] 불필요한 API 제거
    - [x] View 도메인 삭제
- [x] 서비스 계층 추가
