### ISSUE TITLE
신고 기능 구현

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#121]
## 🛠 Issue

- 영상에 대한 신고가 가능하도록 구현해야 합니다
- 슬랙 채널에 신고 기록을 전송하도록 구현해야 합니다

## 📝 To-do

- [x] 신고 도메인 정의
- [x] 신고에 필요한 CRUD 메서드를 서비스 -> 리포지토리에 정의
- [ ] 컨트롤러 정의
- [ ] 슬랙 서비스 정의
- [ ] 신고 서비스 -> 슬랙 서비스에 의존하도록
- [ ] 슬랙 컨트롤러 정의
