### ISSUE TITLE
[feat] 북마크 도메인 정의

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#41]
## 🛠 Issue
- 북마크 도메인 정의

## 📝 To-do
- [x] 북마크 도메인 작성
- [x] 북마크와 관련된 도메인 생각해서 엔티티 작성
- [x] bookmark 로직 작성
- [x] getBookmarkedRecords 로직 작성
- [x] getBookmarkCount 로직 작성
