### ISSUE TITLE
[feat] RecordService 2차 구현

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#46]
## 🛠 Issue

- 구현되지 않은 RecordService 내 행동 나머지를 구현합니다.

## 📝 To-do

- [x] 키워드 리스트로 필터링한 레코드 리스트 조회
- [x] 최근 한 주간 인기 있는 Record 리스트 조회
- [x] 영상 시청 시에 View 데이터 저장
- [x] 사용자 취향 조회
