### ISSUE TITLE
[feat] 구독 도메인 정의

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#47]
## 🛠 Issue
- 사용자 간 구독 가능한 구독 도메인을 정의합니다.

## 📝 To-do

- [ ] 구독 서비스 정의
- [ ] 구독 도메인 정의
- [ ] 구독 테스트 작성
