### ISSUE TITLE
[feat] API 완성 전 마무리 작업

### ISSUE THREAD

**Issue by jinkonu** [Team-Recordy/Recordy-Server#70]
## 🛠 Issue

- API를 완성하는 데에 필요한 마무리 작업을 진행합니다.

## 📝 To-do

- [x] 키워드 한글 인코딩 작업
- [x] 프로필 API에서 팔로잉, 팔로워 수 전달
- [x] 사용자 가입 시 유영 계정을 팔로우하도록
